// TRUSTREADY_AUTOFIX_TARGET: direct-tool-dispatch-v1

// security-boundary: generated by TrustReady repository-autofix/v1.
// Model output is a proposal; this deterministic function owns authority.
function trustreadySecurityBoundary(tool, context = {}) {
  const reasons = []
  const protectedScopes = new Set(['credentials', 'system_prompt', 'secrets', 'cross_tenant_data'])
  if (context.originTrust === 'untrusted') reasons.push('untrusted_origin')
  if (context.actorTenantId && context.tenantId && context.actorTenantId !== context.tenantId) reasons.push('cross_tenant')
  if ((context.requestedScopes ?? []).some((scope) => protectedScopes.has(scope))) reasons.push('protected_scope')
  if (context.containsSensitive === true && context.egressDestination === 'unapproved_model') reasons.push('sensitive_egress')
  const effectful = ['write', 'consequential', 'irreversible'].includes(tool.risk) || tool.external === true
  if (effectful && context.human_approval !== true) reasons.push('human_approval_required')
  return { allowed: reasons.length === 0, reasons }
}

let executorCalls = 0

export const tools = [
  {
    id: 'read_profile',
    name: 'read_profile',
    risk: 'read',
    external: false,
    handler: async (args) => {
      executorCalls += 1
      return { ok: true, profile: { id: args.userId ?? 'user-1' } }
    },
  },
  {
    id: 'send_payment',
    name: 'send_payment',
    risk: 'consequential',
    external: true,
    handler: async (args) => {
      executorCalls += 1
      return { ok: true, transferred: args.amount ?? 100 }
    },
  },
]

export function resetExecutorCalls() {
  executorCalls = 0
}

export function getExecutorCalls() {
  return executorCalls
}

export async function runAgent({ modelProposal, context = {} }) {
  const tool_calls = [modelProposal]
  const call = tool_calls[0]
  const tool = tools.find((item) => item.name === call.tool)
  if (!tool) return { ok: false, status: 'blocked', reason: 'unknown_tool' }
  const args = call.args ?? {}
  // Separate intentionally vulnerable demo target used to prove that the
  // GitHub adapter can create a real remediation PR without mutating the
  // golden CI fixture used by repo-security-orchestrator.test.mjs.
  const authorization = trustreadySecurityBoundary(tool, context)
  if (!authorization.allowed) {
    return { ok: false, status: 'blocked', reason: authorization.reasons[0], reasons: authorization.reasons }
  }
  return tool.handler(args)
}

export const tenantId = 'tenant-a'
