import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { propertiesFromCsv, normaliseCasesInput } from './intake.mjs';
import { nextAction } from '../runtime/next-action.mjs';
import { buildReviewHtml } from './review-package.mjs';
import { finalizePilot } from './finalize.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../../..');
const deployments=path.join(root,'deployments');
const PORT=Number(process.env.HAUSPILOT_OPS_PORT||4317);
const runs=new Map();
fs.mkdirSync(deployments,{recursive:true});

function loadLocalEnv(){const f=path.join(root,'.env.local');if(!fs.existsSync(f))return;for(const line of fs.readFileSync(f,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'');}}
loadLocalEnv();
const validId=id=>/^[a-z0-9][a-z0-9-]{1,48}$/.test(String(id||''));
const dirOf=id=>{if(!validId(id))throw new Error('Ungültige Kunden-ID.');return path.join(deployments,id)};
const json=(file,fallback={})=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}};
const save=(file,obj)=>fs.writeFileSync(file,JSON.stringify(obj,null,2));
const stateFile=id=>path.join(dirOf(id),'ops-state.local.json');
const getState=id=>json(stateFile(id),{});
const setState=(id,patch)=>{const next={...getState(id),...patch,updated_at:new Date().toISOString()};save(stateFile(id),next);return next};
function runNode(args,{cwd=root}={}){return spawnSync(process.execPath,args,{cwd,env:process.env,encoding:'utf8'});}
function parseLastJson(text=''){const starts=[];for(let i=0;i<text.length;i++)if(text[i]==='{')starts.push(i);for(let i=starts.length-1;i>=0;i--){try{return JSON.parse(text.slice(starts[i]))}catch{}}return null;}
function preflight(id){const d=dirOf(id);const r=runNode(['packs/hauspilot/runtime/preflight.mjs',d]);const result=parseLastJson(r.stdout)||{ok:false,errors:['preflight_unreadable'],warnings:[]};return {...result,next:nextAction(result)};}
function info(id){const d=dirOf(id),s=getState(id);if(s.data_deleted_at&&['CLOSED','ACTIVE_MONTHLY'].includes(s.status))return{id,state:s,preflight:{ok:false,errors:[],warnings:[],next:{action:'FERTIG',message:'Pilot abgeschlossen; vereinbarte Pilotdaten wurden gelöscht.'}},files:{cases:false,properties:false,results:false,review:false,report:false,deletion_proof:fs.existsSync(path.join(d,'deletion-proof.local.json'))},api_ready:Boolean(process.env.OPENAI_API_KEY),running:false};const pf=fs.existsSync(d)?preflight(id):{ok:false,errors:['missing_deployment'],warnings:[],next:{action:'STOPP',message:'Kunde wurde noch nicht angelegt.'}};return{id,state:s,preflight:pf,files:{cases:fs.existsSync(path.join(d,'cases.json')),properties:fs.existsSync(path.join(d,'properties.csv')),results:fs.existsSync(path.join(d,'batch-results.local.json')),review:fs.existsSync(path.join(d,'review.html')),report:fs.existsSync(path.join(d,'pilot-report.local.html')),deletion_proof:fs.existsSync(path.join(d,'deletion-proof.local.json'))},api_ready:Boolean(process.env.OPENAI_API_KEY),running:runs.has(id)};}
function listPilots(){return fs.readdirSync(deployments,{withFileTypes:true}).filter(x=>x.isDirectory()&&validId(x.name)).map(x=>info(x.name));}
function body(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>12_000_000){reject(new Error('Upload zu groß.'));req.destroy();}});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(new Error('Ungültige Anfrage.'))}});req.on('error',reject);});}
function reply(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(b)});res.end(b);}
function fail(res,e,status=400){reply(res,status,{ok:false,error:String(e?.message||e)});}
function slugify(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48);}
function sha256(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function purgePilotData(id){const d=dirOf(id),s=getState(id);const names=['cases.json','properties.csv','contractors.csv','vendors.csv','client.json','pilot-approval.json','measurement.json','privacy-manifest.json','batch-results.local.json','review.html','review-decisions.local.json','pilot-report.local.html','run.local.log','START_HERE.md'];const deleted=[];for(const name of names){const f=path.join(d,name);if(!fs.existsSync(f))continue;deleted.push({file:name,sha256:sha256(f)});fs.rmSync(f,{force:true});}const proof={pilot_id:id,company:s.company||'',verdict:s.verdict||null,deleted_at:new Date().toISOString(),deleted_files:deleted,retained_files:['ops-state.local.json','pilot-report.local.summary.json','deletion-proof.local.json'],note:'Application-level deletion from the local pilot workspace; this is not a forensic secure-wipe claim.'};save(path.join(d,'deletion-proof.local.json'),proof);const clean={...s,data_deleted_at:proof.deleted_at,deletion_proof:'deletion-proof.local.json'};delete clean.customer_email;delete clean.reviewer_email;delete clean.reviewer_name;delete clean.operator_name;save(stateFile(id),clean);return proof;}

async function api(req,res,url){
  try{
    if(req.method==='GET'&&url.pathname==='/api/pilots')return reply(res,200,{ok:true,pilots:listPilots()});
    if(req.method==='GET'&&url.pathname==='/api/pilot')return reply(res,200,{ok:true,pilot:info(url.searchParams.get('id'))});
    if(req.method==='POST'&&url.pathname==='/api/create'){
      const b=await body(req);if(b.deposit_paid!==true)throw new Error('Zuerst Zahlungseingang über 1.330 € bestätigen.');
      const company=String(b.company||'').trim();if(!company)throw new Error('Kundenname fehlt.');const id=validId(b.id)?b.id:slugify(company);if(!validId(id))throw new Error('Kunden-ID konnte nicht erzeugt werden.');
      const d=dirOf(id);if(!fs.existsSync(d)){const r=runNode(['packs/hauspilot/new-pilot.mjs','--id',id,'--company',company,'--template',b.template||'repair_intake']);if(r.status!==0)throw new Error(r.stderr||r.stdout||'Pilot konnte nicht angelegt werden.');}
      const approvalPath=path.join(d,'pilot-approval.json'),approval=json(approvalPath,{});Object.assign(approval,{data_mode:b.data_mode||'anonymised',scope_confirmed:true,shadow_only_confirmed:true,operator_named:Boolean(String(b.operator_name||'').trim()),retention_confirmed:true});save(approvalPath,approval);
      setState(id,{company,template:b.template||'repair_intake',reviewer_name:String(b.reviewer_name||''),reviewer_email:String(b.reviewer_email||''),operator_name:String(b.operator_name||''),deposit_paid:true,deposit_eur:1330,status:'WAITING_FOR_DATA',created_at:new Date().toISOString()});
      return reply(res,200,{ok:true,pilot:info(id)});
    }
    if(req.method==='POST'&&url.pathname==='/api/intake'){
      const b=await body(req),id=b.id,d=dirOf(id);if(!fs.existsSync(d))throw new Error('Kunde nicht gefunden.');
      const mode=b.data_mode||'anonymised';if(['pseudonymised_personal_data','authorised_personal_data'].includes(mode)){setState(id,{status:'STOPP_PRIVACY',data_mode:mode});throw new Error('STOPP · Datenschutz-Ausnahme: personenbezogene oder pseudonymisierte Daten laufen nicht im delegierten Standardpfad. Privacy/Owner entscheidet zuerst.');}
      if(!b.properties_text||!b.cases_text)throw new Error('Beispiele und Stammdatenliste werden beide benötigt.');
      const client=json(path.join(d,'client.json'),{}),template=client.pilot?.template;const props=propertiesFromCsv(b.properties_text);if(!props.length)throw new Error('Stammdatenliste enthält keine Objekte.');
      const cases=normaliseCasesInput({template,fileName:b.cases_name||'cases.json',text:b.cases_text,properties:props});
      fs.writeFileSync(path.join(d,'properties.csv'),b.properties_text);save(path.join(d,'cases.json'),cases);
      const approvalPath=path.join(d,'pilot-approval.json'),a=json(approvalPath,{});a.data_mode=mode;a.data_authorised=b.data_authorised===true;a.anonymisation_confirmed=mode==='anonymised'&&b.anonymisation_confirmed===true;save(approvalPath,a);
      const pf=preflight(id);setState(id,{status:pf.ok?'READY_TO_RUN':pf.next.action,case_count:cases.cases.length,data_mode:a.data_mode});return reply(res,200,{ok:true,pilot:info(id)});
    }
    if(req.method==='POST'&&url.pathname==='/api/run'){
      const b=await body(req),id=b.id,d=dirOf(id);if(runs.has(id))throw new Error('Pilot läuft bereits.');const pf=preflight(id);if(!pf.ok)throw new Error(`${pf.next.action}: ${pf.next.message}`);if(!process.env.OPENAI_API_KEY)throw new Error('Einmaliges Admin-Setup fehlt: OPENAI_API_KEY ist auf diesem Rechner nicht konfiguriert.');
      setState(id,{status:'RUNNING',run_started_at:new Date().toISOString(),run_error:null});const log=fs.createWriteStream(path.join(d,'run.local.log'),{flags:'a'});const child=spawn(process.execPath,['packs/hauspilot/run-pilot.mjs',d],{cwd:root,env:process.env});runs.set(id,child);child.stdout.pipe(log);child.stderr.pipe(log);
      child.on('close',code=>{runs.delete(id);log.end();if(code===0){const batch=json(path.join(d,'batch-results.local.json'),{});fs.writeFileSync(path.join(d,'review.html'),buildReviewHtml(batch,{company:getState(id).company,pilot_id:id}));setState(id,{status:'WAITING_FOR_REVIEW',run_finished_at:new Date().toISOString()});}else setState(id,{status:'STOPP',run_finished_at:new Date().toISOString(),run_error:`Technischer Lauf beendet mit Code ${code}. Eskalieren.`});});
      return reply(res,202,{ok:true,pilot:info(id)});
    }
    if(req.method==='POST'&&url.pathname==='/api/finalize'){
      const b=await body(req),id=b.id,d=dirOf(id);const review=JSON.parse(b.review_text||'{}');const result=finalizePilot({pilotDir:d,reviewDoc:review,measurementInput:{cases_per_month:b.cases_per_month,minutes_before:b.minutes_before,minutes_after:b.minutes_after,internal_hourly_cost_eur:b.internal_hourly_cost_eur}});setState(id,{status:'REPORT_READY',verdict:result.summary.verdict,report_ready_at:new Date().toISOString()});return reply(res,200,{ok:true,result,pilot:info(id)});
    }
    if(req.method==='POST'&&url.pathname==='/api/closeout'){
      const b=await body(req),id=b.id,s=getState(id);if(!s.verdict)throw new Error('Zuerst Review und Report abschließen.');
      if(b.continue_monthly===true&&s.verdict!=='KEEP')throw new Error('Monatliche Weiterführung nur nach WEITER/KEEP. Sonst zuerst verbessern oder stoppen.');
      const fee=Number(b.monthly_fee_eur||750);if(b.continue_monthly===true&&fee!==750)throw new Error('Sonderpreis/Sonderscope: nicht selbst entscheiden — Sales eskalieren. Standard ist 750 €/Monat für denselben Workflow.');
      const complete=b.report_delivered===true&&b.final_invoice_sent===true&&b.final_payment_paid===true&&b.delete_pilot_data===true;
      if(b.continue_monthly===true&&complete){const rd=path.join(root,'retainers',id);if(!fs.existsSync(rd)){const r=runNode(['packs/hauspilot/retainer/new-retainer.mjs','--id',id,'--customer',s.company,'--reviewer',s.reviewer_name||'Reviewer','--operator',s.operator_name||'Operations','--workflow',s.template,'--fee','750']);if(r.status!==0)throw new Error(r.stderr||r.stdout||'Monatlicher Betrieb konnte nicht angelegt werden.');}}
      setState(id,{report_delivered:b.report_delivered===true,final_invoice_sent:b.final_invoice_sent===true,final_payment_paid:b.final_payment_paid===true,continue_monthly:b.continue_monthly===true,monthly_fee_eur:b.continue_monthly===true?750:null,status:complete?(b.continue_monthly?'ACTIVE_MONTHLY':'CLOSED'):'CLOSEOUT_OPEN'});if(complete)purgePilotData(id);return reply(res,200,{ok:true,pilot:info(id)});
    }
    return reply(res,404,{ok:false,error:'Nicht gefunden.'});
  }catch(e){fail(res,e)}
}

function fileRoute(res,url){try{const id=url.searchParams.get('id'),kind=url.searchParams.get('kind'),d=dirOf(id);const allowed={review:'review.html',report:'pilot-report.local.html',summary:'pilot-report.local.summary.json',log:'run.local.log',deletion:'deletion-proof.local.json'};const name=allowed[kind];if(!name)throw new Error('Datei nicht erlaubt.');const f=path.join(d,name);if(!fs.existsSync(f))throw new Error('Datei noch nicht vorhanden.');const type=name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.json')?'application/json; charset=utf-8':'text/plain; charset=utf-8';res.writeHead(200,{'content-type':type,'content-disposition':kind==='review'?`attachment; filename="${id}-review.html"`:kind==='report'?`attachment; filename="${id}-pilot-report.html"`:'inline'});fs.createReadStream(f).pipe(res);}catch(e){fail(res,e,404)}}

const page=`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Operations Console</title><style>:root{--bg:#f4f0e8;--p:#fffdf8;--i:#171715;--m:#6b6860;--l:#d9d3c7;--a:#d8ff62;--g:#e9f6d9;--w:#fff0c7;--r:#ffe0dc;--d:#20271f}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--i);font-family:Inter,system-ui,sans-serif}.w{max-width:1080px;margin:auto;padding:24px 16px 80px}h1{font-size:54px;letter-spacing:-.055em;margin:35px 0 8px}.lead{color:var(--m);font-size:19px}.card{background:var(--p);border:1px solid var(--l);border-radius:20px;padding:22px;margin:14px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}label{display:block;font-size:12px;font-weight:800;margin:8px 0 5px}input,select{width:100%;padding:12px;border:1px solid var(--l);border-radius:10px;background:white;font:inherit}input[type=checkbox]{width:auto}.btn{border:0;border-radius:13px;padding:14px 17px;background:var(--d);color:white;font-weight:900;cursor:pointer;text-decoration:none;display:inline-block}.btn.a{background:var(--a);color:var(--i)}.btn[disabled]{opacity:.4;cursor:not-allowed}.status{padding:16px;border-radius:14px;margin:12px 0;background:var(--w)}.ok{background:var(--g)}.bad{background:var(--r)}small,.muted{color:var(--m)}.hide{display:none}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.step{font-size:11px;font-weight:900;background:#eee9df;border-radius:999px;padding:7px 10px}.money{font-size:28px;font-weight:900}@media(max-width:700px){.grid,.three{grid-template-columns:1fr}h1{font-size:42px}}</style></head><body><div class="w"><span class="step">ASSISTANT MODE</span><h1>Was ist mein nächster Schritt?</h1><p class="lead">Standardkunden komplett abarbeiten. Nur Datenschutz-Ausnahme, Technikfehler oder Sonderpreis werden eskaliert.</p>
<div class="card"><h2>1 · Bezahlten Kunden anlegen</h2><div class="grid"><div><label>Kunde</label><input id="company" placeholder="Muster Hausverwaltung GmbH"><label>Workflow</label><select id="template"><option value="repair_intake">Reparaturmeldungen</option><option value="tenant_inbox">Mieterpostfach</option><option value="invoice_review">Rechnungen</option></select><label>Datenmodus</label><select id="dataMode"><option value="anonymised">Anonymisiert (Standard)</option><option value="synthetic">Synthetisch</option><option value="pseudonymised_personal_data">Personenbezogen/pseudonymisiert → STOPP & Privacy</option></select></div><div><label>Reviewer</label><input id="reviewer" placeholder="Name"><label>Reviewer E-Mail</label><input id="reviewerEmail" placeholder="name@kunde.de"><label>Operations Assistant</label><input id="operator" placeholder="Name"><label><input type="checkbox" id="deposit"> Zahlungseingang 1.330 € in Stripe geprüft</label></div></div><button class="btn a" id="create">Kunde starten →</button><div id="createMsg"></div></div>
<div class="card hide" id="work"><h2>2 · Drei Dinge vom Kunden</h2><div class="three"><div><label>20–50 Beispiele (.json oder .csv)</label><input type="file" id="cases" accept=".json,.csv"></div><div><label>Stammdatenliste (.csv)</label><input type="file" id="props" accept=".csv"></div><div><label>Freigabe</label><label><input type="checkbox" id="auth"> Kunde hat diese Daten für den Pilot autorisiert</label><label><input type="checkbox" id="anon"> Bei „anonymisiert“: Anonymisierung geprüft</label></div></div><div class="status">Personenbezogene oder pseudonymisierte Daten gehören nicht in den delegierten Standardpfad. Dann zeigt die Console STOPP und Privacy/Owner übernimmt die Ausnahme.</div><button class="btn" id="check">Prüfen →</button><div class="status" id="next">Noch keine Daten geprüft.</div></div>
<div class="card hide" id="runCard"><h2>3 · Starten</h2><p>Wenn alles grün ist, ein Klick. Preflight, Privacy Manifest, echter Modelllauf und Safety Boundary laufen im Hintergrund.</p><button class="btn a" id="run">Starten →</button><div id="runMsg"></div></div>
<div class="card hide" id="reviewCard"><h2>4 · Kunde prüft</h2><p>Review-Datei sicher an die benannte Person senden. Sie sieht nur <b>Richtig · Ändern · Falsch</b>.</p><a class="btn" id="reviewDownload" href="#">Review-Datei herunterladen</a><hr style="border:0;border-top:1px solid var(--l);margin:20px 0"><label>Zurückgesendete review-decisions.json</label><input type="file" id="reviewFile" accept=".json"><div class="grid"><div><label>Fälle / Monat</label><input id="monthlyCases" type="number"></div><div><label>Minuten / Fall vorher</label><input id="before" type="number" step="0.1"></div><div><label>Minuten / Fall mit Workflow</label><input id="after" type="number" step="0.1"></div><div><label>Interner Stundenwert €</label><input id="rate" type="number" step="0.1" value="35"></div></div><button class="btn a" id="finalize">Ergebnis erzeugen →</button><div id="finalMsg"></div></div>
<div class="card hide" id="closeCard"><h2>5 · Abschluss</h2><div class="row"><a class="btn" id="reportDownload" href="#">Kundenreport herunterladen</a><span id="verdict" class="step"></span></div><p class="money">570 € Restzahlung</p><label><input type="checkbox" id="reportSent"> Kundenreport sicher gesendet</label><label><input type="checkbox" id="invoiceSent"> 570-€-Rechnung in Stripe gesendet</label><label><input type="checkbox" id="finalPaid"> Zahlung eingegangen</label><label><input type="checkbox" id="deleteData"> Pilotdaten jetzt gemäß Retention löschen</label><label><input type="checkbox" id="continue"> Bei „WEITER“: Standardbetrieb 750 €/Monat aktivieren</label><br><button class="btn a" id="close">Abschließen →</button><div id="closeMsg"></div></div>
</div><script>
let current=null;const $=id=>document.getElementById(id);const read=f=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsText(f)});async function post(u,b){const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)}),j=await r.json();if(!j.ok)throw new Error(j.error||'Fehler');return j}function show(id,on=true){$(id).classList.toggle('hide',!on)}function msg(id,t,bad=false){$(id).innerHTML='<div class="status '+(bad?'bad':'ok')+'">'+t+'</div>'}async function refresh(){if(!current)return;const j=await fetch('/api/pilot?id='+current).then(r=>r.json()),p=j.pilot,s=p.state||{};if(p.preflight.next.action==='FERTIG'){msg('closeMsg','✓ Fertig. Pilotdaten gelöscht; Löschbeleg vorhanden.');return}show('work');show('runCard');$('next').textContent=p.preflight.next.action+' · '+p.preflight.next.message;$('next').className='status '+(p.preflight.next.action==='STARTEN'?'ok':p.preflight.next.action==='STOPP'?'bad':'');$('run').disabled=!p.preflight.ok||p.running;if(p.running)msg('runMsg','Pilot läuft. Diese Seite kann offen bleiben.');if(s.status==='WAITING_FOR_REVIEW'||p.files.review){show('reviewCard');$('reviewDownload').href='/file?id='+current+'&kind=review'}if(s.status==='REPORT_READY'||p.files.report){show('closeCard');$('reportDownload').href='/file?id='+current+'&kind=report';$('verdict').textContent=s.verdict||'ERGEBNIS'}if(s.run_error)msg('runMsg',s.run_error,true)}
$('create').onclick=async()=>{try{const j=await post('/api/create',{company:$('company').value,template:$('template').value,data_mode:$('dataMode').value,reviewer_name:$('reviewer').value,reviewer_email:$('reviewerEmail').value,operator_name:$('operator').value,deposit_paid:$('deposit').checked});current=j.pilot.id;msg('createMsg','✓ Kunde angelegt. Jetzt nur die drei Kundendinge einlesen.');refresh()}catch(e){msg('createMsg',e.message,true)}};
$('check').onclick=async()=>{try{const cf=$('cases').files[0],pf=$('props').files[0];if(!cf||!pf)throw new Error('Beispiele und Stammdatenliste auswählen.');await post('/api/intake',{id:current,cases_name:cf.name,cases_text:await read(cf),properties_text:await read(pf),data_mode:$('dataMode').value,data_authorised:$('auth').checked,anonymisation_confirmed:$('anon').checked});await refresh()}catch(e){msg('next',e.message,true)}};
$('run').onclick=async()=>{try{await post('/api/run',{id:current});msg('runMsg','✓ Gestartet. Das System arbeitet; Status wird automatisch aktualisiert.');const timer=setInterval(async()=>{await refresh();const j=await fetch('/api/pilot?id='+current).then(r=>r.json());if(!j.pilot.running){clearInterval(timer);refresh()}},2500)}catch(e){msg('runMsg',e.message,true)}};
$('finalize').onclick=async()=>{try{const f=$('reviewFile').files[0];if(!f)throw new Error('Review-Datei auswählen.');const j=await post('/api/finalize',{id:current,review_text:await read(f),cases_per_month:$('monthlyCases').value,minutes_before:$('before').value,minutes_after:$('after').value,internal_hourly_cost_eur:$('rate').value});msg('finalMsg','✓ Ergebnis fertig. Empfehlung: '+j.result.summary.verdict);refresh()}catch(e){msg('finalMsg',e.message,true)}};
$('close').onclick=async()=>{try{const j=await post('/api/closeout',{id:current,report_delivered:$('reportSent').checked,final_invoice_sent:$('invoiceSent').checked,final_payment_paid:$('finalPaid').checked,delete_pilot_data:$('deleteData').checked,continue_monthly:$('continue').checked,monthly_fee_eur:750});msg('closeMsg','✓ Status: '+j.pilot.state.status+(j.pilot.state.data_deleted_at?' · Pilotdaten gelöscht':''))}catch(e){msg('closeMsg',e.message,true)}};
</script></body></html>`;

const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://localhost:${PORT}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);if(url.pathname==='/file')return fileRoute(res,url);res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(page)});
server.listen(PORT,'127.0.0.1',()=>console.log(`HausPilot Operations Console: http://127.0.0.1:${PORT}\nAPI key configured: ${Boolean(process.env.OPENAI_API_KEY)}\nCustomer data stays in ignored local deployments/.`));
