import fs from 'node:fs';
import path from 'node:path';
import { buildReviewQueue } from '../runtime/review.mjs';

export function buildReviewHtml(batch, meta={}) {
  const queue=buildReviewQueue(batch.rows||[]).map(q=>({
    case_id:q.case_id,
    template:q.template,
    score:q.score,
    result:q.row.result||{},
    ok:q.row.ok!==false
  }));
  const safe=JSON.stringify(queue).replace(/</g,'\\u003c');
  const title=String(meta.company||'Pilot Review').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Review</title><style>
  :root{--bg:#f4f0e8;--paper:#fffdf8;--ink:#171715;--muted:#6b6860;--line:#d9d3c7;--ok:#e9f6d9;--warn:#fff0c7;--bad:#ffe0dc;--dark:#20271f}*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:Inter,system-ui,sans-serif;color:var(--ink)}.w{max-width:850px;margin:auto;padding:28px 16px 70px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.pill{font-size:11px;font-weight:900;background:white;border:1px solid var(--line);border-radius:999px;padding:7px 10px}.card{margin-top:24px;background:var(--paper);border:1px solid var(--line);border-radius:22px;padding:24px}h1{font-size:42px;letter-spacing:-.04em;margin:22px 0 6px}h2{font-size:30px;margin:4px 0 14px}.muted,small{color:var(--muted)}.facts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.fact{background:white;border:1px solid var(--line);border-radius:14px;padding:14px}.fact small{display:block}.summary{margin:14px 0;padding:16px;border-radius:14px;background:#f2eee6}.buttons{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:18px}.buttons button{border:0;border-radius:14px;padding:17px;font:inherit;font-weight:900;cursor:pointer}.yes{background:var(--ok)}.edit{background:var(--warn)}.no{background:var(--bad)}.problem{display:none;margin-top:12px}.problem.show{display:block}select,textarea{width:100%;padding:11px;border:1px solid var(--line);border-radius:10px;font:inherit;margin-top:8px}textarea{min-height:70px}.next{background:var(--dark);color:white;border:0;border-radius:12px;padding:12px 16px;font-weight:900;margin-top:8px}.done{display:none;text-align:center;padding:40px}.done.show{display:block}.download{background:var(--dark);color:white;border:0;border-radius:14px;padding:15px 18px;font-weight:900;cursor:pointer}@media(max-width:600px){.facts,.buttons{grid-template-columns:1fr}h1{font-size:34px}}</style></head><body><div class="w"><div class="top"><b>▦ ${title}</b><span class="pill">Nur prüfen: richtig / ändern / falsch</span></div><h1>Ist das fachlich richtig?</h1><p class="muted">Mehr musst du hier nicht entscheiden. Es werden keine Aktionen ausgeführt.</p><div id="card" class="card"></div><div id="done" class="card done"><h2>✓ Fertig</h2><p>Alle Fälle sind geprüft. Lade die Entscheidungen herunter und sende die Datei an die Operations-Ansprechperson zurück.</p><button class="download" id="download">Entscheidungen herunterladen</button></div></div><script>
const Q=${safe};let i=0;const reviews={};const errors=[['wrong_classification','Falsche Einordnung'],['wrong_property','Falsches Objekt'],['missing_context','Kontext fehlt'],['unsupported_claim','Nicht belegt'],['bad_draft','Entwurf passt nicht'],['wrong_urgency','Dringlichkeit falsch'],['other','Sonstiges']];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){if(i>=Q.length){document.getElementById('card').style.display='none';document.getElementById('done').classList.add('show');return}const q=Q[i],r=q.result||{};document.getElementById('card').innerHTML=`<small>Fall ${i+1} von ${Q.length}</small><h2>${esc(r.classification||'Fall prüfen')}</h2><div class="facts"><div class="fact"><small>Objekt</small><b>${esc(r.property_id||'nicht eindeutig')}</b></div><div class="fact"><small>Nächster Schritt</small><b>${esc(r.proposed_action?.description||'menschlich prüfen')}</b></div></div><div class="summary">${esc(r.summary||'—')}</div><div class="buttons"><button class="yes" data-d="ACCEPT">✓ Richtig</button><button class="edit" data-d="EDIT">✎ Ändern</button><button class="no" data-d="REJECT">✕ Falsch</button></div><div class="problem" id="problem"><select id="err"><option value="">Was stimmt nicht?</option>${errors.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><textarea id="note" placeholder="Kurzer Hinweis (optional)"></textarea><button class="next" id="save">Speichern + nächster Fall</button></div>`;document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>decide(b.dataset.d));}
function decide(d){const q=Q[i];if(d==='ACCEPT'){reviews[q.case_id]={case_id:q.case_id,decision:d,error_class:null,note:'',reviewed_at:new Date().toISOString()};i++;render();return}document.getElementById('problem').classList.add('show');document.getElementById('save').onclick=()=>{const e=document.getElementById('err').value;if(!e)return alert('Bitte kurz auswählen, was nicht stimmt.');reviews[q.case_id]={case_id:q.case_id,decision:d,error_class:e,note:document.getElementById('note').value,reviewed_at:new Date().toISOString()};i++;render();};}
document.getElementById('download').onclick=()=>{const doc={pilot:${JSON.stringify(meta.pilot_id||'pilot')},company:${JSON.stringify(meta.company||'')},generated_at:new Date().toISOString(),reviews:Object.values(reviews)};const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='review-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};render();</script></body></html>`;
}

if (import.meta.url===`file://${process.argv[1]}`){
  const input=path.resolve(process.argv[2]||''); const out=path.resolve(process.argv[3]||'review.html');
  if(!process.argv[2]){console.error('Usage: node review-package.mjs <batch-results.json> [review.html] [company] [pilot_id]');process.exit(2)}
  const batch=JSON.parse(fs.readFileSync(input,'utf8'));
  fs.writeFileSync(out,buildReviewHtml(batch,{company:process.argv[4]||'',pilot_id:process.argv[5]||''}));
  console.log(JSON.stringify({ok:true,out,case_count:(batch.rows||[]).length},null,2));
}
