export const companyPolicy = Object.freeze({
  version: 'company-future-0.1.0',
  hardEscalations: [
    'instruction_injection',
    'privacy_scope_violation',
    'identity_ambiguous',
    'suspected_fraud',
    'sanctioned_counterparty',
  ],
  promotionGates: {
    '3': { minCases: 50, minAcceptanceRate: 0.98, maxCorrectionRate: 0.02, maxUnsafeExecutions: 0 },
    '4': { minCases: 250, minAcceptanceRate: 0.99, maxCorrectionRate: 0.01, maxUnsafeExecutions: 0 },
  },
  actions: {
    'research.source.read': {
      allowedRoles: ['research_agent'],
      allowedPurposes: ['market_intelligence'],
      minAutonomyLevel: 0,
    },
    'research.purchase_data': {
      allowedRoles: ['research_agent'],
      allowedPurposes: ['market_intelligence'],
      minAutonomyLevel: 3,
      approvedCounterpartyOnly: true,
      maxAmount: { currency: 'EUR', value: 5 },
      requiredEvidence: ['vendor_terms_checked', 'source_relevant'],
    },
    'procurement.quote.request': {
      allowedRoles: ['procurement_agent'],
      allowedPurposes: ['vendor_procurement'],
      minAutonomyLevel: 2,
      requiredEvidence: ['vendor_verified'],
    },
    'procurement.order.place': {
      allowedRoles: ['procurement_agent'],
      allowedPurposes: ['vendor_procurement'],
      minAutonomyLevel: 3,
      approvedCounterpartyOnly: true,
      maxAmount: { currency: 'EUR', value: 100 },
      requiredEvidence: ['vendor_verified', 'quote_match'],
    },
    'finance.invoice.pay': {
      allowedRoles: ['ap_agent'],
      allowedPurposes: ['accounts_payable'],
      minAutonomyLevel: 3,
      approvedCounterpartyOnly: true,
      maxAmount: { currency: 'EUR', value: 250 },
      requiredEvidence: ['invoice_match', 'po_match', 'delivery_confirmed'],
    },
    'finance.bank_detail_change': {
      blocked: true,
      allowedRoles: ['ap_agent'],
      allowedPurposes: ['accounts_payable'],
      minAutonomyLevel: 5,
    },
    'customer.refund.issue': {
      allowedRoles: ['customer_ops_agent'],
      allowedPurposes: ['customer_resolution'],
      minAutonomyLevel: 3,
      maxAmount: { currency: 'EUR', value: 50 },
      requiredEvidence: ['customer_entitlement_verified'],
    },
    'sales.crm.update': {
      allowedRoles: ['sales_ops_agent'],
      allowedPurposes: ['pipeline_ops'],
      minAutonomyLevel: 2,
      requiredEvidence: ['source_provenance'],
    },
    'it.access.provision': {
      allowedRoles: ['it_agent'],
      allowedPurposes: ['employee_it'],
      minAutonomyLevel: 3,
      requiredEvidence: ['manager_request', 'identity_verified'],
    },
    'it.super_admin.grant': {
      blocked: true,
      allowedRoles: ['it_agent'],
      allowedPurposes: ['employee_it'],
      minAutonomyLevel: 5,
    },
    'legal.case.prepare': {
      allowedRoles: ['legal_agent'],
      allowedPurposes: ['legal_ops'],
      minAutonomyLevel: 1,
      requiredEvidence: ['source_provenance'],
    },
    'legal.case.update': {
      allowedRoles: ['legal_agent'],
      allowedPurposes: ['legal_ops'],
      minAutonomyLevel: 4,
      requiresApproval: true,
      requiredEvidence: ['source_provenance', 'case_evidence_complete'],
    },
    'property.repair.dispatch': {
      allowedRoles: ['property_agent'],
      allowedPurposes: ['property_ops'],
      minAutonomyLevel: 3,
      approvedCounterpartyOnly: true,
      maxAmount: { currency: 'EUR', value: 200 },
      requiredEvidence: ['tenant_request', 'vendor_verified'],
    },
    'company.high_consequence.commit': {
      allowedRoles: [
        'research_agent',
        'procurement_agent',
        'ap_agent',
        'customer_ops_agent',
        'sales_ops_agent',
        'it_agent',
        'legal_agent',
        'property_agent',
      ],
      allowedPurposes: [
        'market_intelligence',
        'vendor_procurement',
        'accounts_payable',
        'customer_resolution',
        'pipeline_ops',
        'employee_it',
        'legal_ops',
        'property_ops',
      ],
      minAutonomyLevel: 5,
      requiresApproval: true,
      requiredEvidence: ['high_consequence_evidence_complete'],
    },
  },
})

export const earnedAutonomyMetrics = Object.freeze({
  cases: 500,
  acceptanceRate: 0.995,
  correctionRate: 0.004,
  unsafeExecutions: 0,
})
