import fs from 'node:fs'
import path from 'node:path'

export const REPOSITORY_AUTOFIX_VERSION = 'repository-autofix/v1'

const BOUNDARY_SOURCE = `
// security-boundary: generated by TrustReady repository-autofix/v1.
// Model output is a proposal; this deterministic function owns authority.
function trustreadySecurityBoundary(tool, context = {}) {
  const reasons = []
  const protectedScopes = new Set(['credentials', 'system_prompt', 'secrets', 'cross_tenant_data'])
  if (context.originTrust === 'untrusted') reasons.push('untrusted_origin')
  if (context.actorTenantId && context.tenantId && context.actorTenantId !== context.tenantId) reasons.push('cross_tenant')
  if ((context.requestedScopes ?? []).some((scope) => protectedScopes.has(scope))) reasons.push('protected_scope')
  if (context.containsSensitive === true && context.egressDestination === 'unapproved_model') reasons.push('sensitive_egress')
  const effectful = ['write', 'consequential', 'irreversible'].includes(tool.risk) || tool.external === true
  if (effectful && context.human_approval !== true) reasons.push('human_approval_required')
  return { allowed: reasons.length === 0, reasons }
}
`

export function generateRepositoryAutofix({ rootDir, discovery }) {
  const root = path.resolve(rootDir)
  if (discovery?.controls?.deterministicBoundary) {
    return {
      version: REPOSITORY_AUTOFIX_VERSION,
      automatic: true,
      changed: false,
      supported: true,
      reason: 'deterministic_boundary_already_detected',
      changes: [],
    }
  }

  const executorFindings = (discovery?.findings ?? []).filter((item) => item.kind === 'direct_model_to_tool_executor')
  if (executorFindings.length !== 1) {
    return {
      version: REPOSITORY_AUTOFIX_VERSION,
      automatic: false,
      changed: false,
      supported: false,
      reason: executorFindings.length === 0 ? 'no_supported_direct_executor_found' : 'multiple_executor_paths_require_review',
      changes: [],
    }
  }

  const finding = executorFindings[0]
  if (!/\.(mjs|js|ts)$/.test(finding.path)) {
    return {
      version: REPOSITORY_AUTOFIX_VERSION,
      automatic: false,
      changed: false,
      supported: false,
      reason: 'executor_language_not_autofixable_v1',
      changes: [],
    }
  }

  const absolute = path.join(root, finding.path)
  const before = fs.readFileSync(absolute, 'utf8')
  if (!before.includes('TRUSTREADY_AUTOFIX_TARGET: direct-tool-dispatch-v1')) {
    return {
      version: REPOSITORY_AUTOFIX_VERSION,
      automatic: false,
      changed: false,
      supported: false,
      reason: 'executor_shape_not_proven_safe_to_rewrite',
      changes: [],
    }
  }
  if (!before.includes('return tool.handler(args)')) {
    return {
      version: REPOSITORY_AUTOFIX_VERSION,
      automatic: false,
      changed: false,
      supported: false,
      reason: 'expected_dispatch_statement_missing',
      changes: [],
    }
  }

  const marker = '// TRUSTREADY_AUTOFIX_TARGET: direct-tool-dispatch-v1'
  let after = before.replace(marker, `${marker}\n${BOUNDARY_SOURCE.trimEnd()}`)
  after = after.replace(
    'return tool.handler(args)',
    `const authorization = trustreadySecurityBoundary(tool, context)\n  if (!authorization.allowed) {\n    return { ok: false, status: 'blocked', reason: authorization.reasons[0], reasons: authorization.reasons }\n  }\n  return tool.handler(args)`,
  )

  return {
    version: REPOSITORY_AUTOFIX_VERSION,
    automatic: true,
    changed: after !== before,
    supported: true,
    reason: 'insert_deterministic_boundary_before_model_selected_handler',
    changes: [{
      path: finding.path,
      kind: 'insert_security_boundary',
      before,
      after,
    }],
  }
}

export function applyRepositoryAutofix({ rootDir, patch }) {
  if (!patch?.supported) throw new Error(`repository_autofix_not_supported:${patch?.reason ?? 'unknown'}`)
  const root = path.resolve(rootDir)
  for (const change of patch.changes ?? []) {
    const absolute = path.join(root, change.path)
    const current = fs.readFileSync(absolute, 'utf8')
    if (current !== change.before) throw new Error(`repository_autofix_source_drift:${change.path}`)
    fs.writeFileSync(absolute, change.after, 'utf8')
  }
  return { applied: patch.changes?.length ?? 0 }
}

export function patchSummary(patch) {
  return {
    version: patch.version,
    automatic: patch.automatic,
    changed: patch.changed,
    supported: patch.supported,
    reason: patch.reason,
    changes: (patch.changes ?? []).map((change) => ({ path: change.path, kind: change.kind })),
  }
}
