import fs from 'node:fs'
import path from 'node:path'

export const REPOSITORY_AUTOFIX_VERSION = 'repository-autofix/v2'

const JS_BOUNDARY = `
// security-boundary: generated by TrustReady repository-autofix/v2.
function trustreadySecurityBoundary(tool, context = {}) {
  const reasons = []
  const protectedScopes = new Set(['credentials', 'system_prompt', 'secrets', 'cross_tenant_data'])
  if (context.originTrust === 'untrusted') reasons.push('untrusted_origin')
  if (context.actorTenantId && context.tenantId && context.actorTenantId !== context.tenantId) reasons.push('cross_tenant')
  if ((context.requestedScopes ?? []).some((scope) => protectedScopes.has(scope))) reasons.push('protected_scope')
  if (context.containsSensitive === true && context.egressDestination === 'unapproved_model') reasons.push('sensitive_egress')
  const effectful = ['write', 'consequential', 'irreversible'].includes(tool.risk) || tool.external === true
  if (effectful && context.human_approval !== true) reasons.push('human_approval_required')
  return { allowed: reasons.length === 0, reasons }
}
`

const PY_BOUNDARY = `
# security-boundary: generated by TrustReady repository-autofix/v2.
def trustready_authorize_tool_call(tool_name: str, context: dict | None = None) -> dict:
    context = context or {}
    reasons: list[str] = []
    protected = {"credentials", "system_prompt", "secrets", "cross_tenant_data"}
    actor_tenant = context.get("actor_tenant_id") or context.get("actorTenantId")
    tenant = context.get("tenant_id") or context.get("tenantId")
    if actor_tenant and tenant and actor_tenant != tenant:
        reasons.append("cross_tenant")
    if any(scope in protected for scope in (context.get("requested_scopes") or context.get("requestedScopes") or [])):
        reasons.append("protected_scope")
    if context.get("contains_sensitive") is True and context.get("egress_destination") == "unapproved_model":
        reasons.append("sensitive_egress")
    high_consequence = any(token in tool_name.lower() for token in (
        "send", "submit", "publish", "deploy", "transfer", "payment", "refund",
        "delete", "destroy", "write", "update", "create",
    ))
    origin = context.get("origin_trust") or context.get("originTrust")
    if high_consequence and origin == "untrusted":
        reasons.append("untrusted_origin_effect")
    if high_consequence and context.get("human_approval") is not True:
        reasons.append("human_approval_required")
    return {"allowed": not reasons, "reasons": reasons}
`

function unsupported(reason) {
  return { version: REPOSITORY_AUTOFIX_VERSION, automatic: false, changed: false, supported: false, reason, changes: [] }
}

function insertPythonBoundary(before) {
  if (before.includes('trustready_authorize_tool_call')) return before
  const future = 'from __future__ import annotations\n'
  if (before.includes(future)) return before.replace(future, `${future}\n${PY_BOUNDARY.trim()}\n\n`)
  const doc = before.match(/^(["']{3})[\s\S]*?\1\s*\n/)
  if (doc) return `${before.slice(0, doc[0].length)}\n${PY_BOUNDARY.trim()}\n\n${before.slice(doc[0].length)}`
  return `${PY_BOUNDARY.trim()}\n\n${before}`
}

function pythonPatch(before, finding) {
  if (!/class\s+ToolDef\b/.test(before) || !/def\s+run_agent\s*\(/.test(before) || !/tool_def\.handler\(args\)/.test(before)) return unsupported('python_executor_shape_not_proven_safe_to_rewrite')
  const call = /^(\s*)tool_output = tool_def\.handler\(args\)\n\1err = None\n\1cached = False/m
  if (!call.test(before)) return unsupported('python_expected_dispatch_block_missing')
  let after = insertPythonBoundary(before)
  const contextExpr = after.includes('input_payload') ? '(input_payload or {}).get("_trustready_security_context", {})' : 'context'
  after = after.replace(call, (_match, indent) => `${indent}authorization = trustready_authorize_tool_call(tool_name, ${contextExpr})\n${indent}if not authorization["allowed"]:\n${indent}    tool_output = {"error": "security_boundary_blocked", "reasons": authorization["reasons"]}\n${indent}    err = "security_boundary_blocked"\n${indent}    cached = False\n${indent}else:\n${indent}    tool_output = tool_def.handler(args)\n${indent}    err = None\n${indent}    cached = False`)
  return { version: REPOSITORY_AUTOFIX_VERSION, automatic: true, changed: after !== before, supported: true, reason: 'insert_python_deterministic_boundary_before_model_selected_handler', changes: [{ path: finding.path, kind: 'insert_python_security_boundary', before, after }] }
}

function jsPatch(before, finding) {
  if (!before.includes('TRUSTREADY_AUTOFIX_TARGET: direct-tool-dispatch-v1')) return unsupported('executor_shape_not_proven_safe_to_rewrite')
  if (!before.includes('return tool.handler(args)')) return unsupported('expected_dispatch_statement_missing')
  const marker = '// TRUSTREADY_AUTOFIX_TARGET: direct-tool-dispatch-v1'
  let after = before.replace(marker, `${marker}\n${JS_BOUNDARY.trimEnd()}`)
  after = after.replace('return tool.handler(args)', `const authorization = trustreadySecurityBoundary(tool, context)\n  if (!authorization.allowed) {\n    return { ok: false, status: 'blocked', reason: authorization.reasons[0], reasons: authorization.reasons }\n  }\n  return tool.handler(args)`)
  return { version: REPOSITORY_AUTOFIX_VERSION, automatic: true, changed: after !== before, supported: true, reason: 'insert_deterministic_boundary_before_model_selected_handler', changes: [{ path: finding.path, kind: 'insert_security_boundary', before, after }] }
}

export function generateRepositoryAutofix({ rootDir, discovery }) {
  const root = path.resolve(rootDir)
  if (discovery?.controls?.deterministicBoundary) return { version: REPOSITORY_AUTOFIX_VERSION, automatic: true, changed: false, supported: true, reason: 'deterministic_boundary_already_detected', changes: [] }
  const reachable = new Set(discovery?.reachability?.reachableSources ?? [])
  const executorFindings = (discovery?.findings ?? []).filter((item) => item.kind === 'direct_model_to_tool_executor' && (reachable.size === 0 || reachable.has(item.path)))
  if (executorFindings.length !== 1) return unsupported(executorFindings.length === 0 ? 'no_supported_reachable_direct_executor_found' : 'multiple_reachable_executor_paths_require_review')
  const finding = executorFindings[0]
  const absolute = path.join(root, finding.path)
  const before = fs.readFileSync(absolute, 'utf8')
  if (/\.py$/.test(finding.path)) return pythonPatch(before, finding)
  if (/\.(mjs|js|ts)$/.test(finding.path)) return jsPatch(before, finding)
  return unsupported('executor_language_not_autofixable_v2')
}

export function applyRepositoryAutofix({ rootDir, patch }) {
  if (!patch?.supported) throw new Error(`repository_autofix_not_supported:${patch?.reason ?? 'unknown'}`)
  const root = path.resolve(rootDir)
  for (const change of patch.changes ?? []) {
    const absolute = path.join(root, change.path)
    const current = fs.readFileSync(absolute, 'utf8')
    if (current !== change.before) throw new Error(`repository_autofix_source_drift:${change.path}`)
    fs.writeFileSync(absolute, change.after, 'utf8')
  }
  return { applied: patch.changes?.length ?? 0 }
}

export function patchSummary(patch) {
  return { version: patch.version, automatic: patch.automatic, changed: patch.changed, supported: patch.supported, reason: patch.reason, changes: (patch.changes ?? []).map((change) => ({ path: change.path, kind: change.kind })) }
}
